/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gdxmu_controllers_HIDMonitor */

#ifndef _Included_com_gdxmu_controllers_HIDMonitor
#define _Included_com_gdxmu_controllers_HIDMonitor
#ifdef __cplusplus
extern "C" {
#endif
#undef com_gdxmu_controllers_HIDMonitor_HID_ARRIVED
#define com_gdxmu_controllers_HIDMonitor_HID_ARRIVED 1L
#undef com_gdxmu_controllers_HIDMonitor_HID_REMOVED
#define com_gdxmu_controllers_HIDMonitor_HID_REMOVED 2L
/*
 * Class:     com_gdxmu_controllers_HIDMonitor
 * Method:    initHIDMonitor
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_gdxmu_controllers_HIDMonitor_initHIDMonitor
  (JNIEnv *, jobject);

/*
 * Class:     com_gdxmu_controllers_HIDMonitor
 * Method:    updateHIDMonitor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_gdxmu_controllers_HIDMonitor_updateHIDMonitor
  (JNIEnv *, jobject);

/*
 * Class:     com_gdxmu_controllers_HIDMonitor
 * Method:    destroyHIDMonitor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gdxmu_controllers_HIDMonitor_destroyHIDMonitor
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
