/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gdxmu_controllers_Ois */

#ifndef _Included_com_gdxmu_controllers_Ois
#define _Included_com_gdxmu_controllers_Ois
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gdxmu_controllers_Ois
 * Method:    destroyInputManager
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_gdxmu_controllers_Ois_destroyInputManager
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
